  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "mongo-db"
    labels: 
      app: "mongo-db"
  spec: 
    selector: 
      matchLabels: 
        app: "mongo-db"
    replicas: 1
    strategy: 
      type: "Recreate"
    template: 
      metadata: 
        labels: 
          app: "mongo-db"
          
      spec: 
        containers: 
          - name: "mongo-db"
            image: "mongo:latest"
            
            env: 
              - name: "MONGO_INITDB_ROOT_USERNAME"
                valueFrom :
                  secretKeyRef :
                    name : mongodb-secret
                    key :  username
                
              - name: "MONGO_INITDB_ROOT_PASSWORD"
                valueFrom :
                  secretKeyRef :
                    name : mongodb-secret
                    key : password
                
              - name: "MONGO_INITDB_DATABASE"
                valueFrom :
                  configMapKeyRef :
                    name : mongodb-conf
                    key :  database
                
            ports: 
              - containerPort: 27017
                name: "mongo-db"
                
            volumeMounts: 
              - name: "mongodb-persistent-storage"
                mountPath: "/data/db"
                
        volumes: 
          - name: "mongodb-persistent-storage"
            persistentVolumeClaim: 
              claimName: "mongodb-pvc"                